SMS_TEMPLATE = {
    "send_otp": "Hi! Your EyeMyEye verification code is {otp}. It is valid for 15 mins. s80mPWzCpOC"
}

ERROR_500_MSG = "An unexpected server error occurred. Please contact support."

POINTS_VALUE = {
    "prescription_upload": 10,
    "eye_test": 25,
    "fatigue_test": 20
}

FATIGUE_SUGGESTIONS = {
    0: "Follow the 20-20-20 Rule: Every 20 minutes, take a 20-second break and look at something 20 feet away. This helps reduce eye strain from prolonged screen use.\nAdjust Your Screen Settings: Ensure your screen brightness is not too high or too low. Adjust the contrast and font size for comfortable reading. Use blue light filters or software that reduces blue light emission.\nMaintain Proper Lighting: Ensure your room is well-lit to reduce glare and reflections on your screen. Avoid working in a dark room with a bright screen or in an overly bright room.\nBlink Frequently: Make a conscious effort to blink regularly to keep your eyes moist. Use artificial tears if necessary to prevent dryness.\nTake Regular Breaks and Practice Eye Exercises: Take breaks to rest your eyes and practice eye exercises, such as rolling your eyes or focusing on distant objects. Regular breaks help reduce overall eye strain.",
    25: "Follow the 20-20-20 Rule: Every 20 minutes, take a 20-second break and look at something 20 feet away. This helps reduce eye strain from prolonged screen use.\nAdjust Your Screen Settings: Ensure your screen brightness is not too high or too low. Adjust the contrast and font size for comfortable reading. Use blue light filters or software that reduces blue light emission.\nMaintain Proper Lighting: Ensure your room is well-lit to reduce glare and reflections on your screen. Avoid working in a dark room with a bright screen or in an overly bright room.\nBlink Frequently: Make a conscious effort to blink regularly to keep your eyes moist. Use artificial tears if necessary to prevent dryness.\nTake Regular Breaks and Practice Eye Exercises: Take breaks to rest your eyes and practice eye exercises, such as rolling your eyes or focusing on distant objects. Regular breaks help reduce overall eye strain.",
    50: "Follow the 20-20-20 Rule: Every 20 minutes, take a 20-second break and look at something 20 feet away. This helps reduce eye strain from prolonged screen use.\nAdjust Your Screen Settings: Ensure your screen brightness is not too high or too low. Adjust the contrast and font size for comfortable reading. Use blue light filters or software that reduces blue light emission.\nMaintain Proper Lighting: Ensure your room is well-lit to reduce glare and reflections on your screen. Avoid working in a dark room with a bright screen or in an overly bright room.\nBlink Frequently: Make a conscious effort to blink regularly to keep your eyes moist. Use artificial tears if necessary to prevent dryness.\nTake Regular Breaks and Practice Eye Exercises: Take breaks to rest your eyes and practice eye exercises, such as rolling your eyes or focusing on distant objects. Regular breaks help reduce overall eye strain.",
    75: "Follow the 20-20-20 Rule: Every 20 minutes, take a 20-second break and look at something 20 feet away. This helps reduce eye strain from prolonged screen use.\nAdjust Your Screen Settings: Ensure your screen brightness is not too high or too low. Adjust the contrast and font size for comfortable reading. Use blue light filters or software that reduces blue light emission.\nMaintain Proper Lighting: Ensure your room is well-lit to reduce glare and reflections on your screen. Avoid working in a dark room with a bright screen or in an overly bright room.\nBlink Frequently: Make a conscious effort to blink regularly to keep your eyes moist. Use artificial tears if necessary to prevent dryness.\nTake Regular Breaks and Practice Eye Exercises: Take breaks to rest your eyes and practice eye exercises, such as rolling your eyes or focusing on distant objects. Regular breaks help reduce overall eye strain.",
    100: "Follow the 20-20-20 Rule: Every 20 minutes, take a 20-second break and look at something 20 feet away. This helps reduce eye strain from prolonged screen use.\nAdjust Your Screen Settings: Ensure your screen brightness is not too high or too low. Adjust the contrast and font size for comfortable reading. Use blue light filters or software that reduces blue light emission.\nMaintain Proper Lighting: Ensure your room is well-lit to reduce glare and reflections on your screen. Avoid working in a dark room with a bright screen or in an overly bright room.\nBlink Frequently: Make a conscious effort to blink regularly to keep your eyes moist. Use artificial tears if necessary to prevent dryness.\nTake Regular Breaks and Practice Eye Exercises: Take breaks to rest your eyes and practice eye exercises, such as rolling your eyes or focusing on distant objects. Regular breaks help reduce overall eye strain.",
}